server:
  port: 8006
spring:
  application:
    name: consul-payment-service
  # consul 注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 对外暴露的服务名称
        service-name: ${spring.application.name}